# -*- coding: utf-8 -*-

"""
/***************************************************************************
 Pathfinder
                                 A QGIS plugin
 Finds near-optimal paths in raster images
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2022-01-15
        copyright            : (C) 2022 by Noah Mollerstuen
        email                : noah@mollerstuen.com
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""

__author__ = 'Noah Mollerstuen'
__date__ = '2022-01-15'
__copyright__ = '(C) 2022 by Noah Mollerstuen'

# This will get replaced with a git SHA1 when you do a git archive

__revision__ = '$Format:%H$'

import typing as t
import numpy as np
from qgis.PyQt.QtCore import QCoreApplication
from qgis.core import (QgsProject,
                       QgsProcessing,
                       QgsFeatureSink,
                       QgsProcessingAlgorithm,
                       QgsProcessingParameterRasterLayer,
                       QgsProcessingParameterPoint,
                       QgsProcessingParameterNumber,
                       QgsProcessingParameterFeatureSink,
                       QgsWkbTypes,
                       QgsFields,
                       QgsFeature,
                       QgsGeometry,
                       QgsPoint,
                       QgsRectangle)
from osgeo import gdal
import heapq

NEIGHBORS = ((0, 1), (1, 0), (0, -1), (-1, 0))


def point_to_pixel(point: QgsPoint, img_bounds: QgsRectangle, img_width: int, img_height: int) -> (int, int):
    return (
        round((point.x() - img_bounds.xMinimum()) / img_bounds.width() * img_width - 0.5),
        img_height - 1 - round((point.y() - img_bounds.yMinimum()) / img_bounds.height() * img_height - 0.5)
    )


def pixel_to_point(pix: (int, int), img_bounds: QgsRectangle, img_width: int, img_height: int) -> QgsPoint:
    return QgsPoint(
        (pix[0] + 0.5) / img_width * img_bounds.width() + img_bounds.xMinimum(),
        (img_height - 1 - pix[1] + 0.5) / img_height * img_bounds.height() + img_bounds.yMinimum()
    )


def a_star_heuristic(pos1: (int, int), pos2: (int, int)) -> int:
    return abs(pos1[0] - pos2[0]) + abs(pos1[1] - pos2[1])


def get_neighbors(pos: (int, int), occupancy_grid: np.ndarray):
    return [
        p for p in ((pos[0] + n[0], pos[1] + n[1]) for n in NEIGHBORS) if
        0 <= p[0] < occupancy_grid.shape[1] and 0 <= p[1] < occupancy_grid.shape[0] and not occupancy_grid[p[1]][p[0]]
    ]


class PriorityQueue:
    def __init__(self):
        self.elements: t.List[t.Tuple[float, (int, int)]] = []

    def empty(self) -> bool:
        return not self.elements

    def put(self, item: (int, int), priority: float):
        heapq.heappush(self.elements, (priority, item))

    def get(self) -> (int, int):
        return heapq.heappop(self.elements)[1]


class PathfinderAlgorithm(QgsProcessingAlgorithm):
    """
    This is an example algorithm that takes a vector layer and
    creates a new identical one.

    It is meant to be used as an example of how to create your own
    algorithms and explain methods and variables used to do it. An
    algorithm like this will be available in all elements, and there
    is not need for additional work.

    All Processing algorithms should extend the QgsProcessingAlgorithm
    class.
    """

    # Constants used to refer to parameters and outputs. They will be
    # used when calling the algorithm from another algorithm, or when
    # calling from the QGIS console.
    OUTPUT = 'OUTPUT'
    INPUT_IMG = 'INPUT'
    INPUT_POINT1 = 'INPUT_POINT1'
    INPUT_POINT2 = 'INPUT_POINT2'
    INPUT_MIN_VAL = 'INPUT_MIN_VAL'
    INPUT_MAX_VAL = 'INPUT_MAX_VAL'

    def initAlgorithm(self, config):
        """
        Here we define the inputs and output of the algorithm, along
        with some other properties.
        """

        # We add the input raster features source.
        self.addParameter(
            QgsProcessingParameterRasterLayer(
                self.INPUT_IMG,
                self.tr('Input layer')
            )
        )

        self.addParameter(
            QgsProcessingParameterPoint(
                self.INPUT_POINT1,
                self.tr('Starting Point')
            )
        )

        self.addParameter(
            QgsProcessingParameterPoint(
                self.INPUT_POINT2,
                self.tr('Ending Point')
            )
        )

        self.addParameter(
            QgsProcessingParameterNumber(
                self.INPUT_MIN_VAL,
                self.tr('Minimum Passable Value'),
                optional=True
            )
        )

        self.addParameter(
            QgsProcessingParameterNumber(
                self.INPUT_MAX_VAL,
                self.tr('Maximum Passable Value'),
                optional=True
            )
        )

        # We add a feature sink in which to store our processed features (this
        # usually takes the form of a newly created vector layer when the
        # algorithm is run in QGIS).
        self.addParameter(
            QgsProcessingParameterFeatureSink(
                self.OUTPUT,
                self.tr('Output layer')
            )
        )

    def processAlgorithm(self, parameters, context, feedback):
        """
        Here is where the processing itself takes place.
        """

        # Retrieve the feature source and sink. The 'dest_id' variable is used
        # to uniquely identify the feature sink, and must be included in the
        # dictionary returned by the processAlgorithm function.
        inp_img = self.parameterAsRasterLayer(parameters, self.INPUT_IMG, context)
        start_point = self.parameterAsPoint(parameters, self.INPUT_POINT1, context)
        end_point = self.parameterAsPoint(parameters, self.INPUT_POINT2, context)
        min_val = self.parameterAsString(parameters, self.INPUT_MIN_VAL, context)
        max_val = self.parameterAsString(parameters, self.INPUT_MAX_VAL, context)
        try:
            min_val = int(min_val)
        except ValueError:
            min_val = None
        try:
            max_val = int(max_val)
        except ValueError:
            max_val = None

        (sink, dest_id) = self.parameterAsSink(parameters, self.OUTPUT, context, QgsFields(),
                                               geometryType=QgsWkbTypes.Type.LineString, crs=inp_img.crs())

        bounding_rect = inp_img.extent()

        if not bounding_rect.contains(start_point):
            raise ValueError(self.tr("Starting Point must be somewhere within the raster image"))
        if not bounding_rect.contains(end_point):
            raise ValueError(self.tr("Ending Point must be somewhere within the raster image"))

        img_ds = gdal.Open(inp_img.dataProvider().dataSourceUri())
        inp_arr: np.ndarray = img_ds.GetRasterBand(1).ReadAsArray()

        if min_val is not None and max_val is not None:
            occupancy_mat = np.logical_or(inp_arr < min_val, inp_arr > max_val)
        elif min_val is not None:
            occupancy_mat = inp_arr < min_val
        elif max_val is not None:
            occupancy_mat = inp_arr > max_val
        else:
            raise ValueError(self.tr("At least one of minimum and maximum value must be set"))

        start_pos = point_to_pixel(start_point, bounding_rect, occupancy_mat.shape[1], occupancy_mat.shape[0])
        if occupancy_mat[start_pos[1]][start_pos[0]]:
            raise ValueError(self.tr("Starting Point cannot be in an impassable area"))
        end_pos = point_to_pixel(end_point, bounding_rect, occupancy_mat.shape[1], occupancy_mat.shape[0])
        if occupancy_mat[end_pos[1]][end_pos[0]]:
            raise ValueError(self.tr("Ending Point cannot be in an impassable area"))

        # A* Algorithm
        frontier = PriorityQueue()
        frontier.put(start_pos, 0)
        came_from: t.Dict[(int, int), t.Optional[(int, int)]] = {start_pos: None}
        cost_so_far: t.Dict[(int, int), float] = {start_pos: 0}

        starting_heuristic = a_star_heuristic(start_pos, end_pos)
        min_heuristic = starting_heuristic

        print("Starting A*")
        while True:
            if feedback.isCanceled():
                return
            feedback.setProgress((1 - min_heuristic / starting_heuristic) * 100)

            if frontier.empty():
                raise ValueError(self.tr("No path found"))
            current = frontier.get()

            if current == end_pos:
                break

            for next_pos in get_neighbors(current, occupancy_mat):
                new_cost = cost_so_far[current] + 1
                if next_pos not in cost_so_far or new_cost < cost_so_far[next_pos]:
                    cost_so_far[next_pos] = new_cost
                    heuristic = a_star_heuristic(next_pos, end_pos)
                    min_heuristic = min(min_heuristic, heuristic)
                    frontier.put(next_pos, new_cost + heuristic)
                    came_from[next_pos] = current

        print("Reconstructing path")
        current_point = end_pos
        last_point = None
        path = []
        while True:
            if feedback.isCanceled():
                return
            next_point = came_from[current_point]
            if last_point is None or next_point is None or \
                    next_point[0] - current_point[0] != current_point[0] - last_point[0] or \
                    next_point[1] - current_point[1] != current_point[1] - last_point[1]:
                path.append(pixel_to_point(current_point, bounding_rect,
                                           occupancy_mat.shape[1], occupancy_mat.shape[0]))

            if current_point == start_pos:
                break
            last_point = current_point
            current_point = next_point
        print(len(path))

        # Add a feature in the sink
        feature = QgsFeature()
        feature.setGeometry(QgsGeometry.fromPolyline(path))
        sink.addFeature(feature)

        # Return the results of the algorithm. In this case our only result is
        # the feature sink which contains the processed features, but some
        # algorithms may return multiple feature sinks, calculated numeric
        # statistics, etc. These should all be included in the returned
        # dictionary, with keys matching the feature corresponding parameter
        # or output names.
        return {self.OUTPUT: dest_id}

    def name(self):
        """
        Returns the algorithm name, used for identifying the algorithm. This
        string should be fixed for the algorithm, and must not be localised.
        The name should be unique within each provider. Names should contain
        lowercase alphanumeric characters only and no spaces or other
        formatting characters.
        """
        return 'Find Path'

    def displayName(self):
        """
        Returns the translated algorithm name, which should be used for any
        user-visible display of the algorithm name.
        """
        return self.tr(self.name())

    def group(self):
        """
        Returns the name of the group this algorithm belongs to. This string
        should be localised.
        """
        return self.tr(self.groupId())

    def groupId(self):
        """
        Returns the unique ID of the group this algorithm belongs to. This
        string should be fixed for the algorithm, and must not be localised.
        The group id should be unique within each provider. Group id should
        contain lowercase alphanumeric characters only and no spaces or other
        formatting characters.
        """
        return ''

    def tr(self, string):
        return QCoreApplication.translate('Processing', string)

    def createInstance(self):
        return PathfinderAlgorithm()
